spring:
    application:
        name: email_service
    mail:
        host: s.io
        port: 2525
        username: 
        password: 
        properties:
            mail: 
                smtp: 
                    auth: true
                    starttls:
                        enable: true
    jmx:
        enabled: false 
